### ISSUE TITLE
ImportError: libtk8.6.so (solved ✅)

### ISSUE THREAD

**Issue by GameO7er** [Ali-Frh/CFuzzy#1]
سلام بعد از اجرای دستور زیر:
```wget "https://github.com/Ali-Frh/CFuzzy/archive/refs/heads/main.zip" && unzip main.zip && cd CFuzzy-main && python3 main.py```
ارور زیر رو دریافت کردم:
```Traceback (most recent call last):
  File "/home/user/Downloads/YT/CFuzzy-main/main.py", line 4, in <module>
    from tkinter import *
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```
لطفا راهنمایی کنید.
با سپاس

**Comment by GameO7er** [comment]
با سلام با مراجع به[ این لینک](https://stackoverflow.com/q/48504746/7903663) مشکل حل شد.

arch & arch base:
```sudo pacman -S tk```
 Debian, Ubuntu or another Debian-based:
```sudo apt-get install tk```
On Fedora::
```sudo dnf install tk```

امیدوارم مشکل سایر دوستان هم حل بشه. 
با سپاس

**Comment by Ali-Frh** [comment]
بسیار عالی
به ریدمی اضافه میشه
